version: '3.9'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '8080:80'
        volumes:
            - ./public:/var/www/html/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        build: ./docker/php
        container_name: php
        environment:
            CONTAINER_ROLE: app
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - .:/var/www/html

    php-test:
        build: ./docker/php
        container_name: php-test
        environment:
            CONTAINER_ROLE: app
        depends_on:
            mysql-test:
                condition: service_healthy
        volumes:
            - .:/var/www/html

    scheduler:
        build: ./docker/php
        container_name: scheduler
        environment:
            CONTAINER_ROLE: scheduler
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - .:/var/www/html

    worker:
        build: ./docker/php
        container_name: worker
        environment:
            CONTAINER_ROLE: worker
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - .:/var/www/html

    mysql:
        image: 'mysql:8.0'
        container_name: mysql
        ports:
            - '3366:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'procuros'
            MYSQL_DATABASE: 'procuros'
            MYSQL_USER: 'procuros'
            MYSQL_PASSWORD: 'procuros'
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-pprocuros']
            retries: 3
            timeout: 5s
        volumes:
            - 'database:/var/lib/mysql'
            - ./docker/mysql/mysql.cnf:/etc/alternatives/my.cnf:ro

    mysql-test:
        image: 'mysql:8.0'
        container_name: mysql-test
        ports:
            - '3344:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'procuros'
            MYSQL_DATABASE: 'procuros'
            MYSQL_USER: 'procuros'
            MYSQL_PASSWORD: 'procuros'
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-pprocuros']
            retries: 3
            timeout: 5s
        volumes:
            - ./docker/mysql/mysql.cnf:/etc/alternatives/my.cnf:ro

volumes:
    database:
        driver: local
